# SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 dv4all
#
# SPDX-License-Identifier: Apache-2.0

name: e2e tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "authentication/**"
      - "backend-postgrest/**"
      - "database/**"
      - "e2e/**"
      - "frontend/**"
      - "nginx/**"
  pull_request:
    paths:
      - "authentication/**"
      - "backend-postgrest/**"
      - "database/**"
      - "e2e/**"
      - "frontend/**"
      - "nginx/**"

jobs:
  e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.5
        cache: 'npm'
        cache-dependency-path: e2e/package-lock.json
    - name: install dependencies
      working-directory: e2e
      run: npm ci
    - name: install browsers
      working-directory: e2e
      run: npx playwright install --with-deps
    - name: build rsd
      working-directory: .
      run: |
        cp e2e/.env.e2e .env
        docker-compose build
    - name: start rsd
      working-directory: .
      run: |
        docker-compose up -d
        sleep 10
    - name: run e2e tests
      working-directory: e2e
      run: npm run e2e:all
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: e2e/playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: browser state and .env file
        path: |
          e2e/state/
          .env
        retention-days: 30
