# SPDX-FileCopyrightText: 2022 - 2023 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 - 2023 dv4all
# SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all) (dv4all)
# SPDX-FileCopyrightText: 2022 Ewan Cahen (Netherlands eScience Center) <e.cahen@esciencecenter.nl>
# SPDX-FileCopyrightText: 2022 Netherlands eScience Center
#
# SPDX-License-Identifier: Apache-2.0

name: e2e tests macos
on:
  workflow_dispatch:
    inputs:
      browser:
        type: choice
        description: Select browser
        options:
        - chrome
        - msedge
        - firefox
        - webkit
jobs:
  macos-v12:
    timeout-minutes: 30
    name: ${{inputs.browser}} macos v12
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: get playwright version
      id: playwright-version
      working-directory: e2e
      run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV
    - name: cache playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{runner.os}}-playwright-${{env.PLAYWRIGHT_VERSION}}-${{inputs.browser}}
    - name: install dependencies
      working-directory: e2e
      run: npm ci
    - name: install browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      working-directory: e2e
      run: npx playwright install chromium ${{inputs.browser}} --with-deps
    - name: run e2e tests
      working-directory: e2e
      run: npm run e2e:${{inputs.browser}}:dev
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: macos-playwright-report-${{inputs.browser}}
        path: e2e/playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: macos browser ${{inputs.browser}} state
        path: |
          e2e/state/
        retention-days: 30
