# SPDX-FileCopyrightText: 2022 - 2023 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 - 2023 dv4all
# SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all) (dv4all)
# SPDX-FileCopyrightText: 2022 Ewan Cahen (Netherlands eScience Center) <e.cahen@esciencecenter.nl>
# SPDX-FileCopyrightText: 2022 Netherlands eScience Center
#
# SPDX-License-Identifier: Apache-2.0

name: e2e tests chrome
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "authentication/**"
      - "backend-postgrest/**"
      - "database/**"
      - "e2e/**"
      - "frontend/**"
      - "nginx/**"
  pull_request:
    paths:
      - "authentication/**"
      - "backend-postgrest/**"
      - "database/**"
      - "e2e/**"
      - "frontend/**"
      - "nginx/**"

jobs:
  ubuntu-v22:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.5
        cache: 'npm'
        cache-dependency-path: e2e/package-lock.json
    - name: get playwright version
      id: playwright-version
      working-directory: e2e
      run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package-lock.json').dependencies['@playwright/test'].version)")" >> $GITHUB_ENV
    - name: cache playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
    - name: install dependencies
      working-directory: e2e
      run: npm ci
    - name: install browsers
      working-directory: e2e
      run: npx playwright install chromium chrome firefox --with-deps
      if: steps.playwright-cache.outputs.cache-hit != 'true'
    - name: build rsd
      working-directory: .
      run: |
        cp e2e/.env.e2e .env
        docker-compose build --parallel database backend auth frontend nginx
    - name: start rsd
      working-directory: .
      run: |
        docker-compose up --detach --scale scrapers=0
        sleep 5
    - name: run e2e tests in chrome
      working-directory: e2e
      run: npm run e2e:chrome:action
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: e2e/playwright-report/
        retention-days: 30
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: browser state and .env file
        path: |
          e2e/state/
          .env
        retention-days: 30

