# SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 dv4all
#
# SPDX-License-Identifier: Apache-2.0

name: frontend tests

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  pull_request:
    paths:
      - "frontend/**"

jobs:
  fe-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "install node v18.5 and cash yarn"
        uses: actions/setup-node@v3
        with:
          node-version: 18.5
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock
      - name: "install dependencies"
        working-directory: frontend
        run: yarn install --frozen-lockfile
      - name: "run unit test"
        working-directory: frontend
        run: yarn test:coverage
      - name: "run build test"
        working-directory: frontend
        run: yarn build
