# SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 Ewan Cahen (Netherlands eScience Center) <e.cahen@esciencecenter.nl>
# SPDX-FileCopyrightText: 2022 Netherlands eScience Center
# SPDX-FileCopyrightText: 2022 dv4all
#
# SPDX-License-Identifier: Apache-2.0

name: backend api tests

on:
  pull_request:
    paths:
      - "database/**"
      - "backend-postgrest/**"

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "newman tests with docker-compose"
        working-directory: backend-postgrest/tests
        run: |
          docker-compose up \
            --abort-on-container-exit \
            --exit-code-from postgrest-tests
