# SPDX-FileCopyrightText: 2022 Dusan Mijatovic (dv4all)
# SPDX-FileCopyrightText: 2022 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2022 dv4all
#
# SPDX-License-Identifier: Apache-2.0

name: "REUSE Compliance Check"

on:
  # moved to manual
  # pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: "actions/checkout@v2"
    - name: "REUSE Compliance Check"
      uses: "fsfe/reuse-action@v1.1.1"
